services:

  vault:
    image: hashicorp/vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=2bbz80mr1zm0tfrjwxyq7f48ofgky848
    ports:
      - "8200:8200"

  vault-init:
    image: curlimages/curl
    depends_on:
      - vault
    command: >
      sh -c '
        sleep 10 &&
        curl --header "X-Vault-Token: 2bbz80mr1zm0tfrjwxyq7f48ofgky848" \
             --header "Content-Type: application/json" \
             --request POST \
             --data '"'"'{"data": {"seed": "8b10a037120cf37441bd7623da2aa488c21889017ffb4f4d303b9dbcbada5bee"}}'"'"' \
             http://vault:8200/v1/secret/data/mercury-seed &&
        touch /tmp/healthy &&
        tail -f /dev/null
      '
    healthcheck:
      test: ["CMD-SHELL", "test -f /tmp/healthy"]
      interval: 1s
      timeout: 1s
      retries: 30

  lockbox:
    build:
      context: lockbox
      dockerfile: ./Dockerfile
    depends_on:
      - db_lockbox
      - vault-init
    environment:
      - LOCKBOX_DATABASE_URL=postgres://postgres:postgres@db_lockbox:5432/enclave
      - LOCKBOX_PORT=18080
      - KEY_MANAGER=hashicorp_container
      - HASHICORP_CONTAINER_TOKEN=2bbz80mr1zm0tfrjwxyq7f48ofgky848
      - HASHICORP_CONTAINER_URL=http://vault:8200
      - HASHICORP_CONTAINER_PATH=mercury-seed
      - HASHICORP_CONTAINER_MOUNT_POINT=secret
      - HASHICORP_CONTAINER_KEY_NAME=seed
    ports:
      - "18080:18080"

  mercury-server:
    build:
      context: .
      dockerfile: server/Dockerfile
    depends_on:
      - db_server
      - lockbox
    environment:
      BITCOIN_NETWORK: regtest
      LOCKHEIGHT_INIT: 1000
      LH_DECREMENT: 10
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db_server
      DB_PORT: 5432
      DB_NAME: mercury
      BATCH_TIMEOUT: 20
      ENCLAVES: '[{"url": "http://lockbox:18080", "allow_deposit": true}]'
      NOSTR_INFO: '{
        "relay_server": "wss://relay.damus.io/", 
        "relay_interval": 15, 
        "nostr_privkey": "nsec17e0nvplcze4k7q9nazrw0k3aracwhg6vmuareewjp83ta89njw5spjcgzs", 
        "server_url": "http://mercury_server.xyz", 
        "location": "UK",
        "active": true,
        "onchain_payments": false,
        "ln_payments": true,
        "fee": 0.0001,
        "unit": "BTC"
        }'
    ports:
      - "8000:8000"

  db_lockbox:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enclave
    ports:
      - "5433:5432"
    volumes:
      - postgres_lockbox_data:/var/lib/postgresql/data

  db_server:
    image: postgres:16.2
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mercury
    ports:
      - "5432:5432"
    volumes:
      - postgres_server_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "3000:80"
    environment:
      - REACT_APP_MERCURY_SERVER=http://mercury-server:8000
      - REACT_APP_BITCOIN_NETWORK=regtest
      - REACT_APP_LOCKHEIGHT_INIT=1000
      - REACT_APP_LH_DECREMENT=10
      - REACT_APP_BATCH_TIMEOUT=20
      - REACT_APP_ENCLAVES='[{"url": "http://lockbox:18080", "allow_deposit": true}]'
      - REACT_APP_DB_USER=postgres
      - REACT_APP_DB_PASSWORD=postgres
      - REACT_APP_DB_HOST=db_server
      - REACT_APP_DB_PORT=5432
      - REACT_APP_DB_NAME=mercury
      - REACT_APP_LOCKBOX_DB_USER=postgres
      - REACT_APP_LOCKBOX_DB_PASSWORD=postgres
      - REACT_APP_LOCKBOX_DB_HOST=db_lockbox
      - REACT_APP_LOCKBOX_DB_PORT=5432
      - REACT_APP_LOCKBOX_DB_NAME=enclave
      - REACT_APP_LOCKBOX_DATABASE_URL=postgres://postgres:postgres@db_lockbox:5432/enclave
      - REACT_APP_LOCKBOX_PORT=18080
      - REACT_APP_KEY_MANAGER=hashicorp_container
      - REACT_APP_HASHICORP_CONTAINER_TOKEN=2bbz80mr1zm0tfrjwxyq7f48ofgky848
      - REACT_APP_HASHICORP_CONTAINER_URL=http://vault:8200
      - REACT_APP_HASHICORP_CONTAINER_PATH=mercury-seed
      - REACT_APP_HASHICORP_CONTAINER_MOUNT_POINT=secret
      - REACT_APP_HASHICORP_CONTAINER_KEY_NAME=seed
      - REACT_APP_VAULT_DEV_ROOT_TOKEN_ID=2bbz80mr1zm0tfrjwxyq7f48ofgky848
      - REACT_APP_VAULT_PORT=8200
    depends_on:
      - mercury-server

  tor:
    image: dperson/torproxy:latest
    container_name: tor_node
    restart: always
    volumes:
      - ./tor_data:/var/lib/tor # Persist Tor configuration
    environment:
      - USER=tor
      - GROUP=tor
    command: >
      --hidden-service /var/lib/tor/hidden_service
      --hidden-service-dir /var/lib/tor/hidden_service
      --hidden-service-port 80=rest_server:8000
    depends_on:
      - mercury-server

volumes:
  postgres_lockbox_data:
  postgres_server_data:
